export const ADD_REPORT = 'ADD_REPORT';
export const DELETE_REPORT = 'DELETE_REPORT';
export const EDIT_REPORT = 'EDIT_REPORT';
export const DELIVER_REPORTS = 'DELIVER_REPORTS';
export const DELIVER_REPORT = 'DELIVER_REPORTS';
